spring:
  datasource:
    url: jdbc:h2:./recipeDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_ID}
            client-secret: ${GITHUB_SECRET}
            redirect-uri: ${GITHUB_REDIRECT}
            scope:
              - user:email
              - read:user
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT}
            scope:
              - email
              - profile
server:
  use-forward-headers: true
app:
  auth:
    tokenSecret: ${JWT_KEY}
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris: http://localhost:4200/oauth2/redirect

logging:
  level:
    com:
      mcccodeschool: DEBUG
    org:
      springframework: INFO

---
spring:
  profiles: develop
  datasource:
    url: jdbc:h2:/var/recipeDB/recipe
    username: sa
    password:
    driver-class-name: org.h2.Driver
app:
  oauth2:
    authorizedRedirectUris: https://dev.recipe.mcc-code-school.com/oauth2/redirect
---
spring:
  profiles: master
app:
  oauth2:
    authorizedRedirectUris: https://recipe.mcc-code-school.com/oauth2/redirect


